#Promise

### promise有三种状态

- pending 等待中，还没有得到结果
- resolved(fulfilled) 得到了想要的结果，可以继续执行
- rejected 得到并非所愿的结果，拒绝继续执行

		function fn(num) {
		   return new Promise(function(resolve, reject) {
		       if (typeof num == 'number') {
		           resolve();
		       } else {
		           reject();
		       }
		   }).then(function() {
		       console.log('resolve执行之后的回调');
		   }, function() {
		       console.log('reject执行之后的回调');
		   })
		}

### promise简介
1. promise回调函数默认自带两个参数，resolve, reject，这两个参数是函数，执行resolve()会将promise的状态改为resolved，执行reject()会将promise的状态改为rejected

2. resolve或者reject执行之后Promise会返回一个Promise对象，利用这个Promise对象可以链式执行then，所以resolve和reject都会被then捕捉到。then方法可以携带两个参数，且这两个参数都是函数，第一个函数在前面的promise resolve之后执行，第二个参数在前面的promise reject之后执行。
3. then的两个回调函数所接收的参数，分别是前面的promise中resolve 和reject所携带的参数。
4. 如果then前面还有then的话，前面的then，两个回调函数执行后都默认执行下一个then的resolve回调，但是如果想根据具体情况判断执行哪个回调，需要在前面的then里面手动创建一个promise,手动执行resolve活着reject。举两个例子对比一下：这两个示例的区别书fn传的参数数据类型不同。

	
		var fn = function(num) {
	    return new Promise(function(resolve, reject) {
	        if (typeof num == 'number') {
	            resolve(num);
	        } else {
	            reject('not number');
	        }
	    })
		}
	
		fn(2).then(function(num) {
		    console.log('first: ' + num);
		    return new Promise(function(resolve, reject) {
		        if (num > 2){
		        	resolve(num)
		        }else {
		        	reject('less than 2');
		        }
		    });
		},function(errorMsg){
			console.log('first error: ' + errorMsg);
		})
		.then(function(num) {
		    console.log('second: ' + num);
		    return num + 1;
		},function(errorMsg){
			console.log('second error: ' + errorMsg);
		})
		.then(function(num) {
		    console.log('third: ' + num);
		    return num + 1;
		},function(errorMsg){
			console.log('third error: ' + errorMsg);
		});
		----------------
		// 输出结果
		first: 2
		second error: less than 2
		third: undefined
		
		--------------------------------
		|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*|*
		--------------------------------
		
		var fn = function(num) {
		    return new Promise(function(resolve, reject) {
		        if (typeof num == 'number') {
		            resolve(num);
		        } else {
		            reject('not number');
		        }
		    })
		}
	
		fn('2').then(function(num) {
		    console.log('first: ' + num);
		    return new Promise(function(resolve, reject) {
		        if (num > 2){
		        	resolve(num)
		        }else {
		        	reject('less than 2');
		        }
		    });
		},function(errorMsg){
			console.log('type error: ' + errorMsg);
			return new Promise(function(resolve, reject) {
	        reject('go next reject');
	    });
		})
		.then(function(num) {
		    console.log('second: ' + num);
		    return num + 1;
		},function(errorMsg){
			console.log('second error: ' + errorMsg);
		})
		.then(function(num) {
		    console.log('third: ' + num);
		    return num + 1;
		},function(errorMsg){
			console.log('third error: ' + errorMsg);
		});

		----------------
		// 输出结果
		type error: not number
		second error: go next reject
		third: undefined
	
5. Promise.all 当我们需要多个不相关的执行结果都正常的时候才执行下一个动作的时候，可以用这个方法。all接收一个数组作为参数，数组中每个元素是promise对象（通常是返回Promise对象的函数），当所有的promise状态都变为resolve或者reject的时候，才会执行链接在后面的then方法，且该then方法的回调函数的参数是all里面几个promise对象返回的值组成的数组，执行下面的代码验证一下。

		// 封装一个get请求的方法
		function getJSON(url) {
		    return new Promise(function(resolve, reject) {
		        var XHR = new XMLHttpRequest();
		        XHR.open('GET', url, true);
		        XHR.send();

		        XHR.onreadystatechange = function() {
		            if (XHR.readyState == 4) {
		                if (XHR.status == 200) {
		                    try {
		                        var response = JSON.parse(XHR.responseText);
		                        resolve(response);
		                    } catch (e) {
		                        reject(e);
		                    }
		                } else {
		                    reject(new Error(XHR.statusText));
		                }
		            }
		        }
		    })
		}
	
		var url = 'https://hq.tigerbrokers.com/fundamental/finance_calendar/getType/2017-02-26/2017-06-10';
		var url1 = 'https://hq.tigerbrokers.com/fundamental/finance_calendar/getType/2017-03-26/2017-06-10';
	
		function renderAll() {
		    return Promise.all([getJSON(url), getJSON(url1), getJSON(url1)]);
		}
	
		renderAll().then(function(value) {
		    // 建议大家在浏览器中看看这里的value值
		    console.log(value);
		})
		
		----------------
		// 输出结果
		[Object, Object, Object]		


6. Promise.race 与Promise.all相似，区别就是，只要参数中的一个Promise的状态变成resolved或者rejected就可以执行后面的then方法。且该then方法的回调函数的参数是race里面第一个resolve或者rejected的pomise返回的结果，用下面的代码替换上面代码的结尾部分再，验证一下结果。

		function renderRace() {
		    return Promise.race([getJSON(url), getJSON(url1)]);
		}
		
		renderRace().then(function(value) {
		    console.log(value);
		})

### promise的常见使用场景
ajax请求
	我们使用vue1.0的框架ajax请求都是给ajax设置success和error的回调，有时候甚至会在回调里面再进行ajax 请求，这就容易出现回调地狱，不过到了vue2.0新框架就使用了Promise。
	
		apiGet(url, data) {
	      return new Promise((resolve, reject) => {
	        axios.get(url, data).then((response) => {
	          resolve(response.data)
	        }, (response) => {
	          reject(response)
	          _g.closeGlobalLoading()
	          bus.$message({
	            message: '请求超时，请检查网络',
	            type: 'warning'
	          })
	        })
	      })
	    }
	    
	    
	    this.apiGet('admin/groups').then((res) => {
          this.handelResponse(res, (data) => {
            this.groupOptions = data
          })
        })

	